### ISSUE TITLE
Error after upgrade to HA 2024.3.1 

### ISSUE THREAD

**Issue by dcupaiolo** [c99koder/ha-medisafe#90]
After updating to version 2024.3.1 of HA, the medication sensors are not displayed. I attach the log that appears in the debug below.

## Version of the custom_component
 
0.0.3

## Describe the bug

After updating to version 2024.3.1 of HA, the medication sensors are not displayed. I attach the log that appears in the debug below. All sensors show unavailable 

## Debug log

2024-03-19 09:05:36.838 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up medisafe platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/medisafe/sensor.py", line 29, in async_setup_entry
    for idx, ent in enumerate(coordinator.data["medications"]):
                              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'medications'
```

**Comment by dcupaiolo** [comment]
Sé arregló solo luego de unos días
